osx_image: xcode8.3

dist: trusty
sudo: false

language: node_js
node_js: "8"

env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
    - USE_HARD_LINKS=true

os:
  - osx

script:
  - cd client 
  - npm run write-config
  - npm install && npm run package-mac:publish