osx_image: xcode8.3
dist: trusty
sudo: false
language: node_js
node_js: '8'
env:
  global:
  - ELECTRON_CACHE=$HOME/.cache/electron
  - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
  - USE_HARD_LINKS=true
os:
- osx
script:
- cd client
- npm run write-config
- npm install && npm run package-mac
deploy:
  provider: releases
  name: Agora-eEducation-$TRAVIS_TAG
  skip_cleanup: true
  file_glob: true
  file: release/**/*.zip
  on:
    repo: AgoraIO-Usecase/eEducation-with-Electron
    tags: true
  api-key:
    secure: t6MAyTHJIao9VfyUTY4/eEt/KnETp8Dd+JUuPvvvQQPhKvdIsu2x7zJY9KHkzidKMhzXYQZhF4w3kcAmGwKn3Ogwzzc4bPQxjo2u7UAyBYXlNj31FzlS2gSCX3BV9siJ2urKeZycC/8il2vRsgLU7zSnCv5kPL46R5pH3A5SsYBsmdPDSwBkwNX6RrNqwy5mrDTPsZAa1tVHR5mN6P8cMCbthF6tFOsZ/nny9ZwqQRX2Yyo+ziLFiDJP9642i/7Psegmqk+mevUXJeDYa7j3gdGpa52IS9iPVixpVk5UhX70JLqPGTA3bCraIBD55qu9jOxQISd7PtXy1EPDPIVGxNU6JXANRaPPFz3lAegxdN+uKdGYiW88lxxumZoeLvlYClzhgmso4cozcjHUdqj0oSaD8tozTuvX+4MPmsaZmgEjsRscuGXllw3W/tV32g47YAzS2bjv2Ga9UQ7moPdeRBuuKnBN7hm08lnAJFBNj/nRuC5PqaoOlZq/cVsOeJxg3oWzEiQqoO5IxmBJQke6/wTetmeplQ2M/a3RfyXcjQvx278iiivZwr5mRcu8O+pOHAluqzoWjmYof7uGREzmCwKiWaVOmO3JEcNAlf4yJAMilljzByjGWOxWtIFGmJ2+PLDQIsVV0CcSpHp+1XifWX/wjKblsj78DHy+dV4Ztyc=
